name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull hernygood/probando-cosas:latest
    - name: Delete Old docker container
      run: sudo docker rm -f probando-cosas-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name probando-cosas-container hernygood/probando-cosas