name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.TOKEN_CD}}

      - name: build docker image
        run: |
          docker build . --tag ghcr.io/hernanbueno/probando-cosas:latest
          docker push ghcr.io/hernanbueno/probando-cosas:latest

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: ssh into server
        run: |
          sshpass -p ${{secrets.AUTH_PASS}} ssh -o StrictHostKeyChecking=no ${{secrets.AUTH_SERVER}} << EOF
            cd /root/probando-cosas/
            docker login ghcr.io -u hernanbueno -p ${{secrets.TOKEN_CD}}
            docker pull ghcr.io/hernanbueno/probando-cosas:latest
            docker stop probando-cosas && docker rm probando-cosas
            docker run -d \
              --name probando-cosas \
              -p 3000:3000 \
              -w /app \
              --restart always \
              ghcr.io/hernanbueno/probando-cosas:latest
          EOF